<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Incorrect username or password.' => 'اسم المستخدم أو كلمة المرور غير متطابقتان',
	'The combination of Country ID, Arabic City name and English city name has already been taken.' => '',
	'The combination of Arabic Country name, English Country name and Iso Code has already been taken.' => '',
	'This username has already been taken.' => '',
	'This email address has already been taken.' => '',
    'Arabic City Name' => '',
    'Arabic Country Name' => '',
    'Available' => 'متاح',
    'City' => 'المدينة',
    'Country' => 'الدولة',
    'Created At' => 'تاريخ الإنشاء',
    'Description' => 'الوصف',
    'Email' => 'البريد الإلكتروني',
    'End Point Area' => '',
    'End Point City' => '',
    'End Point Time' => '',
    'English City Name' => '',
    'English Country Name' => '',
    'ID' => '',
    'Iso Code' => '',
    'Mobile' => 'رقم الهاتف',
    'Name' => '',
    'Password' => 'كلمة المرور',
    'Start Point Area' => '',
    'Start Point City' => '',
    'Start Point Time' => '',
    'Updated At' => 'تاريخ آخر تعديل',
    'User ID' => '',
    'User Name' => 'اسم المستخدم',
];
